### ISSUE TITLE
Add MDN issue to PR template

### ISSUE THREAD

**Issue by domenic** [whatwg/spec-factory#28]
https://github.com/whatwg/spec-factory/blob/main/PULL_REQUEST_TEMPLATE.md.template should be updated with a new checklist item like:

```markdown
- [ ] [MDN Issue](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) is filed (if applicable): …
```

Then we need to update https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests to give the right instructions for documentation.

@sideshowbarker maybe you could work on the whatwg/meta changes first?

**Comment by annevk** [comment]
@sideshowbarker did this drop of your radar?

**Comment by annevk** [comment]
I merged that, do you want to PR spec-factory? I can probably review today and merge and deploy tomorrow (generates 17 PRs and I'm not sure I want to deal with that today).
