### ISSUE TITLE
New issue templates broke form prefilling of file-issue.js script

### ISSUE THREAD

**Issue by not-my-profile** [whatwg/spec-factory#63]
The HTML spec makes use of the [file-issue.js](https://github.com/whatwg/whatwg.org/blob/main/resources.whatwg.org/file-issue.js) script, which provides a "File an issue about the selected text" link in the bottom right corner that when clicked previously opened the issue form prefilled with the selected text:

```js
    return originalFilingURL + '?title=' + encodeURIComponent(bugData.title) + '&body=' +
           encodeURIComponent(bugData.body);
```

The new issue templates broke this since the `body` URL param no longer works. Fixing this will require four steps:

1. Updating the `data-file-issue-url=` in the HTML `source` file to include `?template=0-new-issue.yml`.
2. Updating the above code of `file-issue.js` to preserve existing URL parameters.
3. Specifying `id: issue-body` below `type: textarea` in `0-new-issue.yml`. (I tested it and unfortunately GitHub ignores the id if it is set to `body`.)
4. Implementing a new `data-body-url-param` option in `file-issue.js` and adding `data-body-url-param="issue-body"` to the HTML `source` file.

While I took the time to figure this out, I'm not interesting in implementing these steps myself ... I'm busy polishing my HTML parser.

**Comment by annevk** [comment]
For me it seems to work fine, it just bypasses the templates. Is the problem here that admins can bypass the templates but other users cannot?

I wonder if we should remove `file-issue.js` as nobody seems to be using it anyway.

cc @zcorpan @domenic

**Comment by domenic** [comment]
> I wonder if we should remove `file-issue.js` as nobody seems to be using it anyway.

I tend to agree. Although I use it myself sometimes, the only use I see from others is the mountains and mountains of spam that I'm pretty sure comes from the file-issue.js links. (It follows the same format, of just the URL of some part of the spec as the body.)

**Comment by not-my-profile** [comment]
I think removing the script (and prefill function) would be fine ... however I do like the "File an issue" link in the corner ... perhaps we could implement the link in HTML so that it's also present without JavaScript?

**Comment by annevk** [comment]
Filed https://github.com/whatwg/whatwg.org/issues/426 on potentially restoring it with CSS. I'm going to remove it for now as it's indeed broken and the CSS replacement isn't necessarily better.

**Comment by zcorpan** [comment]
If it's causing spam then it's probably better to not have it.

**Comment by annevk** [comment]
It's now been removed everywhere. Might take some time to roll out across all standards. There's potential for a CSS-based replacement, but it has some shortcomings as discussed in the issue above.
