### ISSUE TITLE
Add workflow_dispatch to build.yml?

### ISSUE THREAD

**Issue by annevk** [whatwg/spec-factory#67]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch would allow us to manually run a workflow in the event we need it.

We kinda need it now and it seems impossible without creating commits.

**Comment by domenic** [comment]
I think you can just click the re-run button on GitHub jobs?
![image](https://github.com/whatwg/spec-factory/assets/617481/12845b3c-dceb-448b-9f35-38465817c444)

**Comment by domenic** [comment]
Interesting, you can only click that button for builds that have happened recently. (Last 30 days?)

I did that for all the specs for which it's possible, but yeah... let's add this.
