### ISSUE TITLE
`make local/remote` need the COMMIT-SHA macro

### ISSUE THREAD

**Issue by andreubotella** [whatwg/spec-factory#8]
The `local` and `remote` targets of the Makefile template define the `SNAPSHOT-LINK` text macro, which used to define the "snapshot as of this commit" link in the spec metadata. tabatkins/bikeshed#1635, however, removed any usage of that macro, instead using a new `COMMIT-SHA` macro for the LS status, which those Makefile targets don't define.

This would be solved by removing the `SNAPSHOT-LINK` definition and adding one for `COMMIT-SHA` defining it to be the empty string, for example. However, this would create a link pointing to `./commit-snapshots//`, which isn't ideal.

**Comment by annevk** [comment]
A bogus link is the plan in #7. I think that's fine personally. We don't support a full local deploy after all.
